"""The committed Tailwind CSS must match the templates it is built from.

`static/dashboard/css/app.css` is generated by `make css` and committed, so the Docker
image can stay Python-only. The failure mode that catches: someone edits a template,
introduces a utility class, and ships — the class was never generated, so the styling is
silently missing in production. That is exactly what happened between 2026-06-22 and
2026-09-05: 34 templates moved ahead of the build and 36 utilities the templates used
(`file:*` pickers, `border-b-2`, `bg-black/20`, `border-white/5`, …) were absent from
production for about ten weeks. Nothing failed; the pages just looked wrong, worst on
mobile where the sidebar overlay and the responsive-table labels live.

The check is a content hash of Tailwind's own inputs (input.css + config + every class
attribute), not a selector search: escaping `bg-black/40` into `.bg-black\\/40` by hand is
how a naive checker invents false alarms.
"""
from __future__ import annotations

import pytest

from tools import css_inputs_hash


def test_committed_css_is_current_for_the_templates():
    current, stored = css_inputs_hash.compute(), css_inputs_hash.stored()
    if stored is None:
        pytest.fail(
            "static/dashboard/css/.inputs.sha256 is missing — run `make css` and commit "
            "both it and static/dashboard/css/app.css."
        )
    assert current == stored, (
        "The dashboard CSS is stale: templates, input.css or tailwind.config.js changed "
        "since the committed build, so any new utility class is MISSING from "
        "static/dashboard/css/app.css and will silently not apply in production.\n"
        "Fix: run `make css` and commit static/dashboard/css/app.css + "
        "static/dashboard/css/.inputs.sha256."
    )


def test_built_css_is_present_and_non_trivial():
    """A zero-byte or truncated build would leave every page unstyled — cheap sanity net."""
    css = css_inputs_hash.REPO_ROOT / "static" / "dashboard" / "css" / "app.css"
    assert css.exists(), "built dashboard CSS is missing — run `make css`"
    assert css.stat().st_size > 10_000, f"built CSS looks truncated ({css.stat().st_size} bytes)"
