# Generated by Django 5.2.15 on 2026-06-20 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('intake', 'Intake agent'), ('router', 'Router agent'), ('specialist', 'Specialist agent'), ('intelligent_intake', 'Intelligent intake specialist (unsupported)'), ('summarizer', 'Session summarizer'), ('safety', 'Safety classifier (guardrail backstop)'), ('qa', 'QA / assessment agent (v2)')], max_length=32, unique=True)),
                ('body', models.TextField()),
                ('language_directive', models.TextField(blank=True, help_text='Appended {language} block; use {locale} placeholder.')),
                ('model_id', models.CharField(max_length=64)),
                ('prompt_version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Short brand-level note.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kb.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='kb.category')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=160)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternate names/SKUs.')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('search_text', models.CharField(default='', editable=False, max_length=512)),
                ('is_supported', models.BooleanField(default=True, help_text='We service this and have a manual; else intelligent-intake.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='kb.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='kb.vendor')),
            ],
            options={
                'ordering': ['vendor__name', 'model_name'],
                'unique_together': {('vendor', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='MachineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('sv', 'Svenska')], default='en', max_length=5)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('brochure', 'Brochure'), ('wiring', 'Wiring diagram')], default='manual', max_length=16)),
                ('pdf', models.FileField(upload_to='manuals/')),
                ('parsed_text', models.TextField(blank=True)),
                ('token_estimate', models.IntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kb.machine')),
            ],
        ),
        migrations.CreateModel(
            name='QuickReplyChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_step', models.CharField(max_length=32)),
                ('value', models.CharField(help_text='Value sent when tapped.', max_length=120)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='kb.category')),
            ],
            options={
                'ordering': ['intake_step', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BrandNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_notes', to='kb.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_notes', to='kb.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='FAQEntryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('sv', 'Svenska')], max_length=5)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='kb.faqentry')),
            ],
            options={
                'unique_together': {('faq', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='GenericGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('lang', models.CharField(choices=[('en', 'English'), ('sv', 'Svenska')], default='en', max_length=5)),
                ('body', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='kb.category')),
            ],
            options={
                'unique_together': {('category', 'key', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_categories', to='kb.category')),
            ],
            options={
                'verbose_name_plural': 'problem categories',
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='QuickReplyChipText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('sv', 'Svenska')], max_length=5)),
                ('label', models.CharField(max_length=120)),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='kb.quickreplychip')),
            ],
            options={
                'unique_together': {('chip', 'lang')},
            },
        ),
    ]
