# Generated by Django 5.2.15 on 2026-06-21 01:14

import django.db.models.deletion
from django.db import migrations, models

import kb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_trigram'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vvs_installation', 'VVS installation terms'), ('groundwork', 'Groundwork / excavation terms'), ('heatpump_brine', 'Heat pump brine-water villa terms'), ('well_drilling', 'Energy well drilling terms'), ('other', 'Other policy')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('lang', models.CharField(choices=[('en', 'English'), ('sv', 'Svenska')], default='sv', max_length=5)),
                ('pdf', models.FileField(upload_to='terms/')),
                ('parsed_text', models.TextField(blank=True)),
                ('token_estimate', models.IntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('cite_on', models.JSONField(blank=True, default=list, help_text='e.g. ["booking","quote","maintenance","consumer_rights"]')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='machinedocument',
            name='pdf',
            field=models.FileField(upload_to=kb.models.manual_upload_path),
        ),
        migrations.CreateModel(
            name='MachineNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='kb.machine')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
