# Generated by Django 5.2.15 on 2026-06-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_policydocument_alter_machinedocument_pdf_machinenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprompt',
            name='max_output_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='thinking_budget',
            field=models.IntegerField(default=0, help_text='Gemini thinking tokens (0 = off).'),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='thinking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='agent_notes',
            field=models.TextField(blank=True, help_text="Per-vendor guidance appended to the specialist for this vendor's machines (V2)."),
        ),
    ]
