# Generated by Django 5.2.15 on 2026-06-21 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_agentprompt_max_output_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericguide',
            name='kind',
            field=models.CharField(choices=[('faq', 'FAQ'), ('guide', 'Guide'), ('best_practice', 'Best practice')], default='guide', max_length=16),
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('match_severity', models.CharField(blank=True, choices=[('urgent', 'Urgent — safety risk / active property damage'), ('normal', 'Normal — broken/degraded, no immediate danger'), ('service', 'Service — maintenance / advisory / quote')], max_length=16)),
                ('match_keyword', models.CharField(blank=True, help_text='Substring in the problem text (case-insensitive).', max_length=120)),
                ('action', models.CharField(choices=[('troubleshoot', 'Troubleshoot normally'), ('route_maintenance', 'Route to maintenance / service request'), ('urgent_contact', 'Urgent — escalate immediately')], default='route_maintenance', max_length=24)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first.')),
                ('is_active', models.BooleanField(default=True)),
                ('match_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kb.category')),
                ('match_problem_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kb.problemcategory')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
