# Generated by Django 5.2.15 on 2026-06-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_genericguide_kind_routingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, help_text='Source topic (frågeämne) slug.', max_length=64)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('lang', models.CharField(choices=[('en', 'English'), ('sv', 'Svenska')], default='sv', max_length=5)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site FAQ',
                'ordering': ['topic', 'question'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('heat', 'Heat'), ('air', 'Air'), ('water', 'Water'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='other', help_text='Top-level KB grouping (Heat/Air/Water/Hybrid/Other).', max_length=12),
        ),
    ]
