# Generated by Django 5.2.15 on 2026-06-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_set_category_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField(default=dict, help_text='{nodes:[...], edges:[...]}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
