# Generated by Django 5.2.15 on 2026-06-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_flowconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprompt',
            name='faq_categories',
            field=models.ManyToManyField(blank=True, help_text="If set, inject FAQ only from these categories; empty = the matched machine's category.", related_name='+', to='kb.category'),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='inject_faq',
            field=models.BooleanField(default=True, help_text='Inject category FAQ/guides into the specialist context.'),
        ),
    ]
