# Generated by Django 5.2.15 on 2026-06-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0009_agentprompt_faq_categories_agentprompt_inject_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGuardrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('intake', 'Intake agent'), ('router', 'Router agent'), ('specialist', 'Specialist agent'), ('intelligent_intake', 'Intelligent intake specialist (unsupported)'), ('summarizer', 'Session summarizer'), ('safety', 'Safety classifier (guardrail backstop)'), ('qa', 'QA / assessment agent (v2)')], max_length=32)),
                ('rule', models.TextField(help_text='One guardrail rule, in plain language.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'order', 'id'],
            },
        ),
    ]
