# Generated by Django 5.2.15 on 2026-07-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0010_agentguardrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqentry',
            name='applicable_subtypes',
            field=models.JSONField(blank=True, default=list, help_text='Category-leaf slugs this entry applies to; empty = all.'),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Optional — narrows this entry to one manufacturer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kb.vendor'),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='onset_type',
            field=models.CharField(blank=True, help_text='any|sudden|long_term', max_length=12),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='safe_customer_checks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='service_trigger',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, help_text='External id (e.g. FAQ import faq_id) for idempotent re-import.', max_length=32),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='source_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sitefaq',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
