# Generated by Django 5.2.15 on 2026-07-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0012_seed_brand_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentguardrail',
            name='role',
            field=models.CharField(choices=[('intake', 'Intake agent'), ('router', 'Router agent'), ('specialist', 'Specialist agent'), ('intelligent_intake', 'Intelligent intake specialist (unsupported)'), ('intelligent_specialist', 'Intelligent specialist (serviced category, no manual)'), ('summarizer', 'Session summarizer'), ('safety', 'Safety classifier (guardrail backstop)'), ('qa', 'QA / assessment agent (v2)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='agentprompt',
            name='role',
            field=models.CharField(choices=[('intake', 'Intake agent'), ('router', 'Router agent'), ('specialist', 'Specialist agent'), ('intelligent_intake', 'Intelligent intake specialist (unsupported)'), ('intelligent_specialist', 'Intelligent specialist (serviced category, no manual)'), ('summarizer', 'Session summarizer'), ('safety', 'Safety classifier (guardrail backstop)'), ('qa', 'QA / assessment agent (v2)')], max_length=32, unique=True),
        ),
    ]
