# Generated by Django 5.2.15 on 2026-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0014_alter_agentguardrail_role_alter_agentprompt_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.CharField(help_text='e.g. FAQEntry, GenericGuide, SiteFAQ.', max_length=32)),
                ('object_id', models.PositiveIntegerField()),
                ('lang', models.CharField(choices=[('en', 'English'), ('sv', 'Svenska')], default='en', max_length=5)),
                ('scope', models.CharField(help_text='Agent role this embedding is scoped to (kb.corpus registry).', max_length=32)),
                ('content_hash', models.CharField(max_length=64)),
                ('vector', models.JSONField(help_text='768-float embedding vector (core.constants.EMBED_DIM).')),
                ('model_name', models.CharField(help_text='Embedding model that produced this vector.', max_length=64)),
                ('embedded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'source_model'], name='kb_embeddin_scope_752474_idx')],
                'unique_together': {('source_model', 'object_id', 'lang', 'scope')},
            },
        ),
    ]
