# Generated by Django 5.2.15 on 2026-07-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0015_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(default='internal', help_text="Capability kind, e.g. 'internal' (today) or 'mcp' (future).", max_length=16)),
                ('handler_ref', models.CharField(blank=True, help_text='Dotted path to the function/module implementing this tool.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='common_issues',
            field=models.TextField(blank=True, help_text='Freeform notes: common issues & solutions staff have seen for this agent.'),
        ),
        migrations.AddField(
            model_name='agentprompt',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text="Tools this agent may call ('MCP-style' 1-click enable).", related_name='agents', to='kb.tool'),
        ),
    ]
