# Generated by Django 5.2.15 on 2026-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0020_activate_consult_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedocument',
            name='alarm_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='machinedocument',
            name='alarm_scan_sha',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='machinedocument',
            name='documents_alarm_codes',
            field=models.BooleanField(default=False),
        ),
    ]
