# Generated by Django 5.2.15 on 2026-06-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('kb', '0002_trigram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('property_type', models.CharField(blank=True, max_length=60)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('serial', models.CharField(blank=True, max_length=120)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(blank=True, choices=[('urgent', 'Urgent — safety risk / active property damage'), ('normal', 'Normal — broken/degraded, no immediate danger'), ('service', 'Service — maintenance / advisory / quote')], max_length=16)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('troubleshooting_performed', models.JSONField(blank=True, default=list)),
                ('resolved', models.BooleanField(blank=True, null=True)),
                ('service_recommended', models.BooleanField(blank=True, null=True)),
                ('booking_requested', models.BooleanField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, max_length=16)),
                ('state', models.CharField(blank=True, max_length=24)),
                ('reply_turns', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='kb.category')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='chat.conversation')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='crm.customer')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='kb.machine')),
                ('problem_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='kb.problemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('payload_json', models.JSONField(default=dict)),
                ('escalation_reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='crm.session')),
            ],
        ),
        migrations.CreateModel(
            name='LeadDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sink', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='crm.servicerequest')),
            ],
            options={
                'unique_together': {('service_request', 'sink')},
            },
        ),
    ]
