# Generated by Django 5.2.15 on 2026-06-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
    ]
