# Generated by Django 5.2.15 on 2026-06-22 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_phone_hash'),
        ('kb', '0008_flowconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='equipment_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_customers', to='kb.vendor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_customers', to='kb.category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_customers', to='kb.machine'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_summary',
            field=models.TextField(blank=True),
        ),
    ]
