# Generated by Django 5.2.15 on 2026-07-12 18:56

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_equipment_summary_customer_primary_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n8n_webhook_url', models.URLField(blank=True)),
                ('n8n_shared_secret', models.CharField(blank=True, max_length=255)),
                ('n8n_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'integration settings',
            },
        ),
        migrations.AddField(
            model_name='customerfile',
            name='drive_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customerfile',
            name='folder',
            field=models.CharField(default='uploads', max_length=16),
        ),
        migrations.AddField(
            model_name='customerfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerfile',
            name='source',
            field=models.CharField(default='staff', max_length=16),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='file',
            field=models.FileField(upload_to=crm.models.customer_file_path),
        ),
    ]
