# Generated by Django 5.2.15 on 2026-07-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_backfill_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='escalation_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='session',
            name='form_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='session',
            name='form_shown',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='form_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='installer',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='session',
            name='onset',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='service_area_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='session',
            name='service_area_status',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
