# Generated by Django 5.2.15 on 2026-07-14 00:07

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_session_escalation_reason_session_form_category_and_more'),
        ('kb', '0011_faq_approval_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('previous_installer_names', models.JSONField(default=crm.models._default_previous_installers)),
                ('fallback_contact_url', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'geo settings',
            },
        ),
        migrations.CreateModel(
            name='PostcodeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=120)),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('inside', 'Inside'), ('extension', 'Extension')], default='inside', max_length=16)),
                ('polygon', models.JSONField(help_text='Validated GeoJSON Polygon/MultiPolygon geometry (crm.geo.clean_polygon).')),
                ('border_km', models.FloatField(default=10.0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='service_areas', to='kb.category')),
            ],
        ),
    ]
