# Generated by Django 5.2.15 on 2026-07-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_geosettings_postcodearea_servicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.CharField(choices=[('heat_pump', 'Heat pump service'), ('water_pump_well', 'Water pump / well service'), ('water_filtration', 'Water filter service'), ('quote_request', 'Quote request')], max_length=32, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
