# Generated by Django 5.2.15 on 2026-08-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_formbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnrevokedExternalCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_url', models.URLField()),
                ('file_kind', models.CharField(blank=True, max_length=16)),
                ('purged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, help_text='Staff has manually deleted the Drive copy.')),
            ],
            options={
                'ordering': ['-purged_at'],
            },
        ),
    ]
