# Generated by Django 5.2.15 on 2026-07-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VapiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('caller_phone_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('control_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(blank=True, max_length=24)),
                ('outcome', models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('escalation', 'Escalation'), ('callback', 'Callback'), ('abandoned', 'Abandoned'), ('error', 'Error')], max_length=24)),
                ('escalated', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('duration_s', models.IntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('assistant_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('image_sha256', models.CharField(blank=True, max_length=64)),
                ('n_photos', models.IntegerField(default=1)),
                ('call_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('control_url', models.URLField(blank=True, max_length=500)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('phone_hash', 'image_sha256')},
            },
        ),
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=64)),
                ('tool_call_id', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=64)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='webhook', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('call_id', 'tool_call_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VapiObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('assistant', 'Assistant'), ('tool', 'Tool'), ('phone_number', 'Phone number')], max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('vapi_id', models.CharField(blank=True, max_length=64)),
                ('last_provision_hash', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'unique_together': {('kind', 'name')},
            },
        ),
    ]
