r"""Hash every input that changes the built Tailwind CSS.

Why this exists: `static/dashboard/css/app.css` is generated by `make css` and COMMITTED,
so a template edit that introduces a new utility class ships broken styling unless someone
remembers to rebuild. That is not hypothetical — the committed CSS sat at the 2026-06-22
build while 34 templates moved on, and 36 utilities the templates used (file: pickers,
border-b-2, bg-black/20, border-white/5 …) were simply absent from production for ~10 weeks.

The hash covers exactly what Tailwind reads: the input stylesheet, the config, and the
class attributes of every scanned template. Comparing it to the stored value tells you
whether the committed CSS is current, without parsing CSS selectors (escaping `bg-black/40`
→ `.bg-black\/40` by hand is precisely how a naive checker produces false alarms).

    python tools/css_inputs_hash.py            # print the current hash
    python tools/css_inputs_hash.py --write    # store it (done for you by `make css`)
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INPUT_CSS = REPO_ROOT / "static" / "src" / "input.css"
CONFIG = REPO_ROOT / "tailwind.config.js"
TEMPLATES = REPO_ROOT / "templates"
STAMP = REPO_ROOT / "static" / "dashboard" / "css" / ".inputs.sha256"

_CLASS_ATTR = re.compile(r'class="([^"]*)"')


def compute() -> str:
    h = hashlib.sha256()
    for f in (INPUT_CSS, CONFIG):
        h.update(f.read_bytes())
    # Only the class attributes matter — prose, copy and template logic do not change the
    # generated CSS, so editing wording must not spuriously invalidate the build.
    for tpl in sorted(TEMPLATES.rglob("*.html")):
        text = tpl.read_text(encoding="utf-8")
        for m in _CLASS_ATTR.finditer(text):
            h.update(m.group(1).encode("utf-8"))
    return h.hexdigest()


def stored() -> str | None:
    return STAMP.read_text(encoding="utf-8").strip() if STAMP.exists() else None


def main() -> int:
    current = compute()
    if "--write" in sys.argv:
        STAMP.parent.mkdir(parents=True, exist_ok=True)
        STAMP.write_text(current + "\n", encoding="utf-8")
        print(f"wrote {STAMP.relative_to(REPO_ROOT)} = {current[:12]}…")
        return 0
    print(current)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
